# slim means lighweight python, smaller container, faster to build.
# python image
FROM python:3.12-slim  
# where to put the files inside container
WORKDIR /app        
# copying, first . means everything in my project folder, second . means put it in currenet directory inside the container    
COPY . .  
# run the requirements              
RUN pip install --no-cache-dir -r requirements.txt 
# same port as api port
EXPOSE 8000             
# the server, find the app,  accept connections from outside the conainer, listen to port 8000, run 2 parallel worker
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]
    