"""
AWS Bedrock client for invoking Claude in the FinSight RAG pipeline.

What AWS Bedrock is
-------------------
AWS Bedrock is a managed service that provides API access to foundation models
(FMs) from multiple providers — Anthropic, Amazon, Cohere, Meta — without
requiring you to manage the underlying infrastructure. You call a single AWS
regional endpoint and Bedrock routes the request to the chosen model.

How the Anthropic API works on Bedrock
--------------------------------------
Bedrock accepts Claude requests via its own "converse" or "invoke_model" REST
API, which wraps the standard Anthropic Messages format. Internally the
service translates the Bedrock-native JSON into Anthropic's wire format.

The payload sent to Bedrock (via boto3 bedrock-runtime) is:
  {
    "anthropic_version": "bedrock-2023-05-31",
    "max_tokens": <int>,
    "system": <str>,
    "messages": [{"role": "user", "content": <str>}],
    "temperature": <float>
  }

The response body contains:
  {
    "content": [{"type": "text", "text": "..."}],
    "usage": {"input_tokens": ..., "output_tokens": ...}
  }

Authentication
--------------
boto3 resolves credentials in this order (standard AWS credential chain):
  1. Environment variables: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY,
     AWS_SESSION_TOKEN (for temporary credentials).
  2. Shared credentials file: ~/.aws/credentials
  3. IAM role attached to the EC2 / ECS / EKS task executing the code.

For local development without AWS credentials, BedrockClient automatically
falls back to a stub mode that returns canned responses. Set the environment
variable BEDROCK_STUB=true to force stub mode explicitly.

Usage
-----
    from rag_pipeline.generation.bedrock_client import BedrockClient

    client = BedrockClient()
    response = client.invoke(
        prompt="What are JPMorgan's AML obligations under the Bank Secrecy Act?",
        system_prompt="You are a financial compliance expert.",
    )
    print(response.text)
    print(f"Tokens: {response.input_tokens} in / {response.output_tokens} out")
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import Any

# ── AWS SDK ────────────────────────────────────────────────────────────────────
# boto3 is the AWS SDK for Python. bedrock-runtime is the service client that
# handles model inference requests (as opposed to bedrock, which manages model
# listing and fine-tuning).
try:
    import boto3
    from botocore.exceptions import ClientError, NoCredentialsError, NoRegionError
    _BOTO3_AVAILABLE = True
except ImportError:
    _BOTO3_AVAILABLE = False

# ── Configuration ──────────────────────────────────────────────────────────────
# anthropic.claude-sonnet-4-6-20250514-v1:0 is the Bedrock model ID for
# Claude Sonnet 4.6 in us-east-1. Model IDs are region-specific on Bedrock.
MODEL_ID = "us.anthropic.claude-haiku-4-5-20251001-v1:0"
AWS_REGION = os.environ.get("AWS_REGION", "us-east-1")

# Bedrock requires this version string in every request body — it pins the
# Anthropic wire-format version that Bedrock should use to decode the payload.
ANTHROPIC_VERSION = "bedrock-2023-05-31"

# Sensible defaults for the compliance Q&A use case
DEFAULT_MAX_TOKENS = 2048
DEFAULT_TEMPERATURE = 0.0   # deterministic answers for factual compliance queries


# ─────────────────────────────────────────────────────────────────────────────
# RESPONSE DATACLASS
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class InvokeResponse:
    """
    Structured response from a single Claude invocation.

    Fields
    ------
    text          : str   The model's reply text.
    model_id      : str   The Bedrock model ID that generated the response.
    input_tokens  : int   Number of tokens consumed from the prompt.
    output_tokens : int   Number of tokens generated by the model.
    is_stub       : bool  True when the response is a local stub (no AWS call).
    stop_reason   : str   Why the model stopped: "end_turn", "max_tokens", etc.
    """
    text: str
    model_id: str
    input_tokens: int
    output_tokens: int
    is_stub: bool = False
    stop_reason: str = "end_turn"

    def __repr__(self) -> str:
        stub_tag = " [STUB]" if self.is_stub else ""
        return (
            f"InvokeResponse{stub_tag}("
            f"model={self.model_id!r}, "
            f"tokens={self.input_tokens}+{self.output_tokens}, "
            f"stop={self.stop_reason!r}, "
            f"text={self.text[:80]!r}{'...' if len(self.text) > 80 else ''})"
        )


# ─────────────────────────────────────────────────────────────────────────────
# BEDROCK CLIENT
# ─────────────────────────────────────────────────────────────────────────────

class BedrockClient:
    """
    Single-instance wrapper around boto3's bedrock-runtime client.

    Instantiate once at application startup (boto3 session creation is cheap,
    but keeping a single client avoids redundant credential resolution on
    every request). Falls back to stub mode automatically when AWS credentials
    are not available so local development works without an AWS account.
    """

    def __init__(
        self,
        model_id: str = MODEL_ID,
        region: str = AWS_REGION,
        stub_mode: bool | None = None,
    ) -> None:
        """
        Parameters
        ----------
        model_id  : str
            Bedrock model identifier. Must include the version suffix, e.g.
            "anthropic.claude-sonnet-4-6-20250514-v1:0".
        region    : str
            AWS region where the model is deployed. Bedrock model availability
            varies by region — us-east-1 and us-west-2 have the broadest
            Anthropic model coverage.
        stub_mode : bool | None
            Force stub mode on (True) or off (False). None = auto-detect:
            checks boto3 availability and credential validity at init time.
        """
        self.model_id = model_id
        self.region = region
        self._client = None

        # Explicit override → respect it.
        if stub_mode is True or os.environ.get("BEDROCK_STUB", "").lower() == "true":
            self._stub_mode = True
            print("BedrockClient: stub mode ON (forced via BEDROCK_STUB env or constructor)")
            return

        if stub_mode is False:
            self._stub_mode = False
            self._client = self._build_client()
            return

        # Auto-detect: try to build a real client; fall back to stub on any
        # credential or import error.
        self._stub_mode, self._client = self._auto_init()

        status = "stub" if self._stub_mode else f"live ({region})"
        print(f"BedrockClient ready  model={model_id}  mode={status}")

    # ── Public: invoke ────────────────────────────────────────────────────────

    def invoke(
        self,
        prompt: str,
        system_prompt: str = "",
        max_tokens: int = DEFAULT_MAX_TOKENS,
        temperature: float = DEFAULT_TEMPERATURE,
    ) -> InvokeResponse:
        """
        Send a single user message to Claude and return the full response.

        In live mode, this makes one HTTPS call to the Bedrock regional
        endpoint and blocks until the model finishes generating. For streaming
        responses (e.g. to push tokens to a UI in real time), use
        invoke_stream() instead.

        Parameters
        ----------
        prompt        : str   The user's question or instruction.
        system_prompt : str   Optional system-level instruction that persists
                              across the conversation (sets Claude's persona,
                              constraints, output format, etc.).
        max_tokens    : int   Hard ceiling on generated tokens. Default 2048
                              gives ~1500 words — enough for a detailed
                              compliance answer with cited paragraphs.
        temperature   : float Sampling temperature in [0.0, 1.0].
                              0.0 = deterministic / most probable token.
                              >0.5 = more creative / varied output.
                              For factual RAG answers, use 0.0–0.2.

        Returns
        -------
        InvokeResponse
            Structured result with text, token counts, and metadata.
        """
        if self._stub_mode:
            return self._stub_response(prompt, system_prompt, max_tokens, temperature)
        return self._live_invoke(prompt, system_prompt, max_tokens, temperature)

    # ── Public: invoke_stream ─────────────────────────────────────────────────

    def invoke_stream(
        self,
        prompt: str,
        system_prompt: str = "",
        max_tokens: int = DEFAULT_MAX_TOKENS,
        temperature: float = DEFAULT_TEMPERATURE,
    ):
        """
        Stream Claude's response token-by-token.

        Yields incremental text chunks as the model generates them, then
        yields a final InvokeResponse with the full accumulated text and
        token counts. Callers can push chunks to a WebSocket or SSE stream
        for low-latency UX.

        In stub mode, yields the full stub text as a single chunk followed
        by the summary InvokeResponse.

        Yields
        ------
        str           : Each incremental text chunk from the model.
        InvokeResponse: Final summary object (last yielded item).
        """
        if self._stub_mode:
            stub = self._stub_response(prompt, system_prompt, max_tokens, temperature)
            yield stub.text
            yield stub
            return

        body = self._build_body(prompt, system_prompt, max_tokens, temperature)

        # invoke_model_with_response_stream returns an EventStream; each event
        # contains a "chunk" key with a Base64-encoded JSON delta payload.
        response = self._client.invoke_model_with_response_stream(
            modelId=self.model_id,
            contentType="application/json",
            accept="application/json",
            body=json.dumps(body),
        )

        full_text = []
        input_tokens = 0
        output_tokens = 0
        stop_reason = "end_turn"

        for event in response["body"]:
            chunk = json.loads(event["chunk"]["bytes"])
            event_type = chunk.get("type", "")

            if event_type == "content_block_delta":
                delta = chunk.get("delta", {}).get("text", "")
                full_text.append(delta)
                yield delta

            elif event_type == "message_delta":
                stop_reason = chunk.get("delta", {}).get("stop_reason", stop_reason)

            elif event_type == "message_start":
                usage = chunk.get("message", {}).get("usage", {})
                input_tokens = usage.get("input_tokens", 0)

            elif event_type == "message_delta":
                usage = chunk.get("usage", {})
                output_tokens = usage.get("output_tokens", output_tokens)

        yield InvokeResponse(
            text="".join(full_text),
            model_id=self.model_id,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            stop_reason=stop_reason,
        )

    # ── Private: live invocation ──────────────────────────────────────────────

    def _live_invoke(
        self,
        prompt: str,
        system_prompt: str,
        max_tokens: int,
        temperature: float,
    ) -> InvokeResponse:
        """Build the request body, call Bedrock, parse the response."""
        body = self._build_body(prompt, system_prompt, max_tokens, temperature)

        # invoke_model is the synchronous (non-streaming) call. Bedrock buffers
        # the full response and returns it in a single HTTP response body once
        # generation is complete.
        raw = self._client.invoke_model(
            modelId=self.model_id,
            contentType="application/json",
            accept="application/json",
            body=json.dumps(body),
        )

        # The response body is a streaming object; read() returns raw bytes.
        response_body: dict[str, Any] = json.loads(raw["body"].read())

        # Extract the first (and typically only) text content block.
        # Bedrock always returns content as a list of typed blocks.
        text = "".join(
            block["text"]
            for block in response_body.get("content", [])
            if block.get("type") == "text"
        )

        usage = response_body.get("usage", {})

        return InvokeResponse(
            text=text,
            model_id=self.model_id,
            input_tokens=usage.get("input_tokens", 0),
            output_tokens=usage.get("output_tokens", 0),
            stop_reason=response_body.get("stop_reason", "end_turn"),
        )

    @staticmethod
    def _build_body(
        prompt: str,
        system_prompt: str,
        max_tokens: int,
        temperature: float,
    ) -> dict[str, Any]:
        """
        Construct the Bedrock-flavoured Anthropic Messages API request body.

        The top-level structure is Bedrock-specific (requires anthropic_version).
        The messages array and system field follow the standard Anthropic format.
        """
        body: dict[str, Any] = {
            "anthropic_version": ANTHROPIC_VERSION,
            "max_tokens": max_tokens,
            "temperature": temperature,
            "messages": [
                {"role": "user", "content": prompt},
            ],
        }
        # Only include system if non-empty — Bedrock errors on an empty string.
        if system_prompt:
            body["system"] = system_prompt
        return body

    # ── Private: initialisation helpers ──────────────────────────────────────

    def _build_client(self):
        """Create a boto3 bedrock-runtime client using the ambient credential chain."""
        return boto3.client("bedrock-runtime", region_name=self.region)

    def _auto_init(self) -> tuple[bool, Any]:
        """
        Try to build a live client; return (stub_mode, client).

        boto3 does not validate credentials at client creation time — it only
        fails on the first actual API call. We make a cheap dry-run by calling
        get_caller_identity() on STS (the lowest-cost AWS validation call) to
        catch missing credentials early rather than on the first inference request.
        """
        if not _BOTO3_AVAILABLE:
            print(
                "BedrockClient: boto3 not installed — falling back to stub mode.\n"
                "Install with: pip install boto3"
            )
            return True, None

        try:
            # STS get_caller_identity validates that credentials exist and are
            # syntactically valid. It does NOT check Bedrock permissions, but
            # it confirms that an AWS identity is present.
            sts = boto3.client("sts", region_name=self.region)
            sts.get_caller_identity()

            # Credentials look valid — build the real Bedrock client.
            return False, self._build_client()

        except NoCredentialsError:
            print(
                "BedrockClient: no AWS credentials found — falling back to stub mode.\n"
                "Set AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY to use live Bedrock."
            )
            return True, None

        except NoRegionError:
            print(
                f"BedrockClient: no AWS region configured (tried {self.region}) "
                "— falling back to stub mode.\nSet AWS_REGION env variable."
            )
            return True, None

        except ClientError as exc:
            # ClientError is raised for auth failures (ExpiredToken, AccessDenied).
            # These indicate credentials exist but are invalid or lack permissions.
            code = exc.response.get("Error", {}).get("Code", "")
            print(
                f"BedrockClient: AWS auth error ({code}) — falling back to stub mode.\n"
                f"Details: {exc}"
            )
            return True, None

        except Exception as exc:
            # Network errors (EndpointResolutionError, ConnectTimeout) also land here.
            # Stub mode keeps local development functional with no internet access.
            print(
                f"BedrockClient: unexpected error during AWS init ({type(exc).__name__}: {exc}) "
                "— falling back to stub mode."
            )
            return True, None

    # ── Private: stub mode ────────────────────────────────────────────────────

    def _stub_response(
        self,
        prompt: str,
        system_prompt: str,
        max_tokens: int,
        temperature: float,
    ) -> InvokeResponse:
        """
        Return a canned InvokeResponse without calling AWS.

        The stub text is contextual: it mentions the first 60 chars of the
        prompt so callers can verify routing without a live AWS account.
        Token counts are estimated (4 chars ≈ 1 token) to keep downstream
        logic that gates on token budgets working in tests.
        """
        stub_text = (
            f"[STUB] This response was generated locally without calling AWS Bedrock. "
            f"Model: {self.model_id}  Region: {self.region}\n\n"
            f"Your question: \"{prompt[:120]}{'...' if len(prompt) > 120 else ''}\"\n\n"
            "In a live environment, Claude would retrieve the relevant SEC filing "
            "excerpts and synthesise a detailed compliance answer here. To enable "
            "live inference, configure AWS credentials (AWS_ACCESS_KEY_ID, "
            "AWS_SECRET_ACCESS_KEY, AWS_REGION) and ensure the IAM role has "
            "bedrock:InvokeModel permission on the target model ARN."
        )

        # Rough token estimate: 4 chars ≈ 1 token (GPT-family heuristic, close
        # enough for budget calculations in tests and monitoring dashboards).
        estimated_input = (len(prompt) + len(system_prompt)) // 4
        estimated_output = len(stub_text) // 4

        return InvokeResponse(
            text=stub_text,
            model_id=self.model_id,
            input_tokens=estimated_input,
            output_tokens=estimated_output,
            is_stub=True,
            stop_reason="end_turn",
        )


# ─────────────────────────────────────────────────────────────────────────────
# CLI DEMO
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    client = BedrockClient()

    SYSTEM = (
        "You are a financial compliance expert specialising in SEC filings, "
        "AML regulations, and Basel III capital requirements. Answer questions "
        "precisely and cite relevant regulatory frameworks where applicable."
    )

    queries = [
        "What are the Bank Secrecy Act obligations for large financial institutions "
        "regarding suspicious activity report filings?",
        "Explain the Basel III CET1 capital ratio requirements and how JPMorgan "
        "manages its capital buffers.",
        "What fraud detection controls do banks disclose in their 10-K filings "
        "for card-not-present transactions?",
    ]

    for q in queries:
        print(f"\n── Query: {q[:80]}...")
        r = client.invoke(prompt=q, system_prompt=SYSTEM)
        print(f"   [{r.model_id}]  {r.input_tokens}→{r.output_tokens} tokens  "
              f"stop={r.stop_reason}  stub={r.is_stub}")
        print(f"   {r.text[:300].strip()}{'...' if len(r.text) > 300 else ''}")

    print("\n── Streaming demo ──")
    chunks = []
    for item in client.invoke_stream(
        prompt="Summarise the key AML risk disclosures banks include in their annual reports.",
        system_prompt=SYSTEM,
    ):
        if isinstance(item, str):
            chunks.append(item)
        else:
            print(f"\n[stream complete]  {item.input_tokens}→{item.output_tokens} tokens")
    print("Streamed text:", "".join(chunks)[:200])
